### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by gal-orlanczyk** [hironytic/XMLPullitic#9]
Hi,  

I saw the podspec has support for tvOS commented out is there an issue with using it for tvOS or a particular reason it is commented? 
could this be added for upcoming minor release?

Thanks,
Gal

**Comment by hironytic** [comment]
@gal-orlanczyk Thanks for your request.

The main reason not to support tvOS is that I have never developed apps for tvOS. So I don't know if it works on tvOS.

**Comment by gal-orlanczyk** [comment]
you don't use special API that tvOS doesn't have from what I see, would be great if you could add this.
It doesn't even involve UI so you got nothing to worry if it complies.

**Comment by hironytic** [comment]
OK, I'll give it a try to add support for tvOS. Please give me some time 🙂

**Comment by hironytic** [comment]
I pushed the changes into `tvos-support` branch.

@gal-orlanczyk  Could you check this works on tvOS? You can install it via CocoaPods by putting below line in your podfile.

```ruby
pod 'XMLPullitic', :git => 'https://github.com/hironytic/XMLPullitic.git', :commit => 'ac031227e33fc9645fb1ff197e81466b6c0a2a78'
```

**Comment by gal-orlanczyk** [comment]
@hironytic, The project complies fine

**Comment by gal-orlanczyk** [comment]
@hironytic , Also I ran my unit tests which uses the parser and everything went smooth! 
Would appreciate if you release a version when you could.  Thanks a lot for the help and fast response!

**Comment by hironytic** [comment]
Great! 👍 
I'll merge it and publish to CocoaPods repo.
